# Generated by Django 4.0.4 on 2022-05-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
